FROM node:20 as dev
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG BUILD_ENV=docker
RUN echo "BUILD_ENV is $BUILD_ENV"
RUN npm run build --configuration=$BUILD_ENV

FROM nginx:1.25
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY --from=dev /app/dist/thai-tuan-erp2025.client/browser/ ./
COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]