namespace ThaiTuanERP2025.Domain.Expense.Enums
{
	public enum ExpensePaymentCommentType
	{
		Normal = 0,         // Người dùng nhập bình thường
		System = 1,         // Hệ thống tự động thêm (VD: "Phiếu chuyển sang trạng thái Approved")
		AutoGenerated = 2   // Tự sinh bởi logic nghiệp vụ khác (VD: workflow engine)
	}

}
